export const PRIVACY_POLICY = `# Privacy Policy

**Lucky Stop Inc. / Cliff Industries**
Last updated: June 7, 2026

---

Lucky Stop Inc. ("we", "our", or "us") operates the Lucky Stop mobile application — a loyalty and rewards platform for Lucky Stop gas stations and convenience stores. This policy explains what personal information we collect, why we collect it, how we protect it, and your rights. By using the app, you agree to the practices described here.

---

## 1. Who We Are

Lucky Stop Inc. operates approximately 12 Lucky Stop gas station and convenience store locations. The app is developed and maintained by Cliff Industries on behalf of Lucky Stop Inc.

For privacy inquiries: **support@luckystop.cliffindus.com**

---

## 2. Information We Collect

**Information you provide:**

- **Phone number** — required to create and verify your account via one-time passcode (OTP). This is your primary account identifier.
- **Display name** — optional. Shown in the app and to store staff when they scan your QR code.
- **Recovery email** — optional. Used only if you need to recover your account.
- **Profile photo** — optional avatar image stored securely.
- **Business information** — only if you apply to advertise: business name, description, contact phone, website, and logo.

**Information generated by using the app:**

- **Unique QR code** — an opaque identifier assigned to your account. Never contains personal data.
- **Transaction history** — store, purchase amount, product category, cashback earned, and timestamp for each rewarded purchase.
- **Rewards balance** — your running total of cashback credits earned and redeemed.
- **Redemption history** — records of credits redeemed for in-store products.
- **Receipt photos** — uploaded by store employees to verify your transactions. You do not upload these.
- **Missing-points dispute reports** — your description and approximate details when you report a missing cashback.
- **Product requests** — items you ask a store to stock.
- **Push notification token** — a device token used to deliver notifications. Never shared externally.
- **App crash and error data** — anonymous technical logs used to fix bugs. Does not identify you.

**What we do NOT collect:**

- Precise GPS location or background location tracking
- Payment card numbers or financial account information
- Biometric data (fingerprints or face geometry) — biometric login is handled entirely by your device and the result is never sent to our servers
- Contacts, calendar, or other device app data
- Data from children under 13

---

## 3. How We Collect Your Data

- **Directly from you** — when you create an account, update your profile, submit a dispute, or request a product.
- **From store staff** — when a cashier scans your QR code, enters a purchase amount, or uploads a receipt photo.
- **Automatically** — push notification tokens are generated by Firebase when you log in. Crash data is collected automatically when the app encounters an error.

---

## 4. How We Use Your Data

- Operate your rewards account and calculate cashback credits
- Verify purchases and prevent fraudulent point claims
- Send push notifications (account updates, promotions) — you may opt out at any time in device settings
- Display store-specific offers and promotions
- Respond to disputes and support requests
- Improve the app and fix bugs (using anonymous crash data)
- Comply with legal obligations

---

## 5. Who Can See Your Data

Access within the Lucky Stop system is strictly controlled by role:

- **You (customer)** — your own balance, transactions, redemptions, disputes, and profile only.
- **Cashier / Employee** — your display name and rewards balance only when they scan your QR code. They cannot browse accounts.
- **Store Manager** — transaction history for customers at their assigned store(s) only. Cannot see other stores.
- **Lucky Stop HQ** — aggregated data across all stores for operations, analytics, and fraud investigation.
- **System Administrator** — full access for maintenance and security, with all actions logged and audited.

We do **not** sell, rent, or trade your personal information to any third party.

---

## 6. Third-Party Service Providers

We use the following providers who process your data only on our behalf:

- **Firebase Authentication (Google)** — phone number OTP verification
- **Firebase Cloud Messaging (Google)** — push notification delivery
- **Firebase Storage / AWS S3** — secure storage for receipt photos, avatars, and images
- **PostgreSQL (Neon)** — encrypted database hosting
- **Render** — cloud hosting for the backend API
- **Vercel** — hosting for the admin dashboard

We do not use advertising networks or data brokers.

---

## 7. Data Retention

- **Account profile** — until you delete your account
- **Transaction history** — until account deletion, or 5 years for legal compliance (whichever is longer)
- **Receipt photos** — automatically deleted 12 months after the transaction date
- **Dispute reports** — 24 months from submission
- **Push notification tokens** — stale tokens deleted after 90 days of inactivity
- **Crash and error logs** — 90 days, stored anonymously
- **Deleted accounts** — fully purged within 30 days, except where retention is legally required

---

## 8. Your Rights

- **Access** — request a copy of the personal information we hold about you
- **Correction** — update your name, email, and photo directly in Profile → Account Settings
- **Deletion** — delete your account in Profile → Delete My Account, or contact us. Processed within 30 days.
- **Portability** — request an export of your data (JSON or CSV)
- **Opt out of push notifications** — disable in device Settings → Notifications → Lucky Stop
- **Withdraw consent** — where we rely on consent, you may withdraw at any time
- **Lodge a complaint** — with your local data protection authority if you believe we have acted unlawfully

To exercise any right, contact: **support@luckystop.cliffindus.com**
We respond within 30 days for data rights requests.

---

## 9. Push Notifications

We may send notifications for:

- Cashback confirmations when points are added
- Special offers and limited-time promotions
- Updates on disputes or product requests
- Operational updates (for store employees)

Opt out at any time in device Settings → Notifications → Lucky Stop. This does not affect your rewards account.

---

## 10. Biometric & Device Features

Biometric login (fingerprint or face) is handled entirely by your device's operating system. We never receive, store, or transmit your biometric data — only a pass/fail result from your device.

Your language preference (English or Español) is stored locally on your device and is never sent to our servers.

---

## 11. Children's Privacy

The Lucky Stop app is not directed at children under 13. We do not knowingly collect personal information from children under 13. If you believe a child has created an account, contact us immediately and we will delete the account and all associated data.

---

## 12. California Residents (CCPA)

If you are a California resident, you have the right to:

- **Know** — what personal information we collect, its sources, our purpose for collecting it, and who we share it with
- **Delete** — request deletion of your personal information, subject to legal exceptions
- **Opt out of sale** — we do not sell personal information; no opt-out is required
- **Non-discrimination** — we will never deny service or charge different prices because you exercised a CCPA right

To submit a California privacy request, email **support@luckystop.cliffindus.com** with the subject line "California Privacy Request". We will verify your identity and respond within 45 days.

---

## 13. Security

We protect your data with:

- **HTTPS/TLS encryption** — all data in transit is encrypted
- **Encryption at rest** — database records and files are encrypted at the infrastructure level
- **Token-based authentication** — short-lived access tokens; no passwords stored
- **Role-based access control** — each role can only access the minimum data required
- **Audit logging** — sensitive actions (point grants, account changes, deletions) are logged immutably
- **Private image storage** — receipt photos are stored in private buckets with no public URL

If you believe your account has been compromised, contact us immediately.

---

## 14. Changes to This Policy

When we make material changes, we will update the date at the top of this policy and send a push notification summarizing the key changes. Continued use of the app after changes take effect constitutes acceptance.

---

## Contact Us

**Lucky Stop Customer Support**
Email: support@luckystop.cliffindus.com
Response time: within 2 business days for general inquiries; within 30 days for data rights requests.`;
