// The Lucky Stop offer pictures (1200 x 600, the subject in the middle), served from admin/public/offer-images. Made 2026-10-05 from
// Microsoft Fluent Emoji 3D (MIT licence: public/offer-images/LICENSE.txt). Generated by the offer_art script; do not edit by hand.
export type OfferImage = { category: string; src: string; label: string };

export const OFFER_IMAGES: OfferImage[] = [
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-1-shopping-cart.webp",
    "label": "Shopping cart"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-2-shopping-bags.webp",
    "label": "Shopping bags"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-3-bread.webp",
    "label": "Bread"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-4-glass-of-milk.webp",
    "label": "Glass of milk"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-5-chocolate-bar.webp",
    "label": "Chocolate bar"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-6-popcorn.webp",
    "label": "Popcorn"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-7-cookie.webp",
    "label": "Cookie"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-8-candy.webp",
    "label": "Candy"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-9-cup-with-straw.webp",
    "label": "Cup with straw"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-10-egg.webp",
    "label": "Egg"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-11-cheese-wedge.webp",
    "label": "Cheese wedge"
  },
  {
    "category": "GROCERIES",
    "src": "/offer-images/groceries/groceries-12-bubble-tea.webp",
    "label": "Bubble tea"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-1-ice-cream.webp",
    "label": "Ice cream"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-2-soft-ice-cream.webp",
    "label": "Soft ice cream"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-3-pizza.webp",
    "label": "Pizza"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-4-shaved-ice.webp",
    "label": "Shaved ice"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-5-ice.webp",
    "label": "Ice"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-6-snowflake.webp",
    "label": "Snowflake"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-7-soft-ice-cream.webp",
    "label": "Soft ice cream"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-8-ice-cream.webp",
    "label": "Ice cream"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-9-shaved-ice.webp",
    "label": "Shaved ice"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-10-pizza.webp",
    "label": "Pizza"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-11-snowflake.webp",
    "label": "Snowflake"
  },
  {
    "category": "FROZEN_FOODS",
    "src": "/offer-images/frozen_foods/frozen-foods-12-ice.webp",
    "label": "Ice"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-1-red-apple.webp",
    "label": "Red apple"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-2-green-salad.webp",
    "label": "Green salad"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-3-sandwich.webp",
    "label": "Sandwich"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-4-banana.webp",
    "label": "Banana"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-5-strawberry.webp",
    "label": "Strawberry"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-6-watermelon.webp",
    "label": "Watermelon"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-7-grapes.webp",
    "label": "Grapes"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-8-carrot.webp",
    "label": "Carrot"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-9-avocado.webp",
    "label": "Avocado"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-10-pineapple.webp",
    "label": "Pineapple"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-11-cherries.webp",
    "label": "Cherries"
  },
  {
    "category": "FRESH_FOODS",
    "src": "/offer-images/fresh_foods/fresh-foods-12-peach.webp",
    "label": "Peach"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-1-fuel-pump.webp",
    "label": "Fuel pump"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-2-automobile.webp",
    "label": "Automobile"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-3-oncoming-automobile.webp",
    "label": "Oncoming automobile"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-4-sport-utility-vehicle.webp",
    "label": "Sport utility vehicle"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-5-money-with-wings.webp",
    "label": "Money with wings"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-6-motorway.webp",
    "label": "Motorway"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-7-dollar-banknote.webp",
    "label": "Dollar banknote"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-8-key.webp",
    "label": "Key"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-9-coin.webp",
    "label": "Coin"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-10-racing-car.webp",
    "label": "Racing car"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-11-motorcycle.webp",
    "label": "Motorcycle"
  },
  {
    "category": "GAS",
    "src": "/offer-images/gas/gas-12-fuel-pump.webp",
    "label": "Fuel pump"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-1-articulated-lorry.webp",
    "label": "Articulated lorry"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-2-delivery-truck.webp",
    "label": "Delivery truck"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-3-tractor.webp",
    "label": "Tractor"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-4-pickup-truck.webp",
    "label": "Pickup truck"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-5-fuel-pump.webp",
    "label": "Fuel pump"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-6-oil-drum.webp",
    "label": "Oil drum"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-7-bus.webp",
    "label": "Bus"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-8-articulated-lorry.webp",
    "label": "Articulated lorry"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-9-construction.webp",
    "label": "Construction"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-10-delivery-truck.webp",
    "label": "Delivery truck"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-11-key.webp",
    "label": "Key"
  },
  {
    "category": "DIESEL",
    "src": "/offer-images/diesel/diesel-12-dollar-banknote.webp",
    "label": "Dollar banknote"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-1-hot-dog.webp",
    "label": "Hot dog"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-2-pizza.webp",
    "label": "Pizza"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-3-burrito.webp",
    "label": "Burrito"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-4-hot-beverage.webp",
    "label": "Hot beverage"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-5-taco.webp",
    "label": "Taco"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-6-hamburger.webp",
    "label": "Hamburger"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-7-french-fries.webp",
    "label": "French fries"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-8-poultry-leg.webp",
    "label": "Poultry leg"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-9-doughnut.webp",
    "label": "Doughnut"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-10-croissant.webp",
    "label": "Croissant"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-11-steaming-bowl.webp",
    "label": "Steaming bowl"
  },
  {
    "category": "HOT_FOODS",
    "src": "/offer-images/hot_foods/hot-foods-12-tamale.webp",
    "label": "Tamale"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-1-wrapped-gift.webp",
    "label": "Wrapped gift"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-2-money-bag.webp",
    "label": "Money bag"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-3-party-popper.webp",
    "label": "Party popper"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-4-four-leaf-clover.webp",
    "label": "Four leaf clover"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-5-trophy.webp",
    "label": "Trophy"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-6-admission-tickets.webp",
    "label": "Admission tickets"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-7-gem-stone.webp",
    "label": "Gem stone"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-8-balloon.webp",
    "label": "Balloon"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-9-confetti-ball.webp",
    "label": "Confetti ball"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-10-hundred-points.webp",
    "label": "Hundred points"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-11-glowing-star.webp",
    "label": "Glowing star"
  },
  {
    "category": "OTHER",
    "src": "/offer-images/other/other-12-coin.webp",
    "label": "Coin"
  }
];
