-- AlterTable
ALTER TABLE "stores" ADD COLUMN     "labelGapX" DOUBLE PRECISION NOT NULL DEFAULT 3.175,
ADD COLUMN     "labelGapY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "labelHeight" DOUBLE PRECISION NOT NULL DEFAULT 25.4,
ADD COLUMN     "labelWidth" DOUBLE PRECISION NOT NULL DEFAULT 66.675;

