-- AlterEnum
ALTER TYPE "LabelTemplate" ADD VALUE 'CLEARANCE';
ALTER TYPE "LabelTemplate" ADD VALUE 'INDEPENDENCE_DAY';
ALTER TYPE "LabelTemplate" ADD VALUE 'HALLOWEEN';
ALTER TYPE "LabelTemplate" ADD VALUE 'PREMIUM';
